extends Control


# Called when the node enters the scene tree for the first time.
func _ready():
	#$CenterContainer/VBoxContainer/Button05.button_up.connect( _on_quit )
	#$CenterContainer/VBoxContainer/Button01.button_up.connect( _on_play )
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass

func _on_quit():
	get_tree().quit()
	
func _on_play():
	get_tree().change_scene_to_file("res://scenes/main.tscn")

