extends Node

var game_name: String = "pDash"
var game_version: float = 0.1

## Resources
var lvl_paths: Array[String] = [
	"res://scenes/levels/level_0.tscn",
	"res://scenes/levels/level_1.tscn"
]

## Variables
const STARTING_LIVES: int = 3

## Preferences
var show_splash: bool = false

func fade( type: String , t: float ):
	var fade = load("res://scenes/ui/fade.tscn").instantiate();
	if type == "in":
		fade.type = 0
	elif type == "out":
		fade.type = 1
	fade.speed = 1/t
	get_node("/root/Main/Curtains").add_child( fade )

func splash():
	var splash = load("res://scenes/ui/Splash.tscn").instantiate();
	get_node("/root/Main/Splash").add_child( splash )
	await  splash.get_node("AnimationPlayer").animation_finished
